server:
  port: 8081
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/springvue?useUnicode=true&characterEncodeing=utf-8
    username: Mitea
    password: hello
    driver-class-name: com.mysql.cj.jdbc.Driver
